name: Create Kaniko Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Kaniko version to build'
        required: false
        default: 'v1.23.2'
  push:
    tags:
      - 'kaniko-*'

jobs:
  build-kaniko:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          make git gcc \
          overlayroot fuse zstd xz-utils \
          libselinux-dev libseccomp-dev libssl-dev

    - name: Build Kaniko with all features
      run: |
        git clone https://github.com/GoogleContainerTools/kaniko.git
        cd kaniko
        git checkout ${{ github.event.inputs.version || 'v1.23.2' }}
        make GO_BUILD_FLAGS="-tags=ecr,gcr,acr"
        
        # Create system emulation directories
        mkdir -p kaniko-release/system
        mkdir -p kaniko-release/system/{proc,dev,sys,etc,tmp}
        
        # Create minimal system files
        echo "root:x:0:0:root:/root:/bin/sh" > kaniko-release/system/etc/passwd
        echo "0 0 0 0 0 0 0 0 0 0" > kaniko-release/system/proc/stat
        echo "none / / 0 0" > kaniko-release/system/proc/mountinfo
        touch kaniko-release/system/dev/null
        
        # Package the binary with system emulation
        cp out/executor kaniko-release/
        chmod +x kaniko-release/executor
        tar czvf kaniko-bin.tar.gz kaniko-release/

        # Create directory for kaniko settings
        cd ~
        pwd
        mkdir -p /kaniko/.docker

    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: kaniko-${{ github.event.inputs.version || 'v1.23.2' }}
        name: Kaniko ${{ github.event.inputs.version || 'v1.23.2' }} (with system emulation)
        body: "Standalone Kaniko binary with system emulation"
        files: kaniko/kaniko-bin.tar.gz
