name: Build Kaniko Standalone Action
on:
  push:
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for git operations

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build action
      run: npm run build

    - name: Commit dist folder
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Check if there are changes in dist folder
        if git diff --quiet --exit-code -- dist/; then
          echo "No changes in dist folder to commit"
        else
          git add dist/
          git commit -m "Build: Update dist folder [skip ci]"
          git push origin HEAD:main
        fi
