name: Build and push to GHCR
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Docker Config
      run: |
        mkdir -p /tmp/kaniko/.docker
        export DOCKER_CONFIG=/tmp/kaniko/.docker
        echo '{"auths":{"ghcr.io":{"auth":"$(echo -n ${{ github.actor }}:${{ secrets.TOKEN }} | base64)"}}}' > /tmp/kaniko/.docker/config.json
        
    - name: Build with Kaniko
      uses: pravinmane85/kaniko-standalone@main
      with:
        version: 'v1.23.2'
        destination: 'ghcr.io/pravinmane85/nodejs-18.19.0:${{ github.sha }}'
        emulate-system: 'true'
      env:
        REGISTRY_HOST: ghcr.io
        REGISTRY_USERNAME: ${{ github.actor }}
        REGISTRY_PASSWORD: ${{ secrets.TOKEN }}
