name: Build Image with Kaniko System Emulation
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with Kaniko
      uses: your-username/kaniko-standalone-action@v1
      with:
        version: 'v1.12.0'
        destination: 'ghcr.io/your-username/your-image:${{ github.sha }}'
        emulate-system: 'true'
      env:
        REGISTRY_HOST: ghcr.io
        REGISTRY_USERNAME: ${{ github.actor }}
        REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
